---
title: "Gapminder Exercise Template"
author: "Graham Tierney"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 7)
```


## Load packages

```{r message=FALSE}
library(tidyverse)
```

## Load data

```{r}
gap <- read_csv("https://bit.ly/gap_data_upd")
```

## Exercises

### Exercise 1

How many observations are in this dataset?

```{r nrow, include = F}
num_rows <- nrow(gap)
str_c(c("There are ",num_rows," rows in the data"),collapse = "")
```

There are `r num_rows` rows in the data. 

### Exercise 2

Visualize the relationship between GDP and life expectancy for 
countries in Europe in 1952 using a scatter plot.

```{r eu_52}

eu_52 <- gap %>% filter(continent == "Europe",year== 1952) %>% ggplot() + 
  geom_point(aes(x=gdpPercap,y=lifeExp)) + 
  labs(title = "GDP and Life Expectancy in Europe",
       x = "GDP per Capita",
       y = "Life Expectancy") + 
  theme(plot.title = element_text(hjust = .5))

eu_52

```

### Exercise 3

Add year 1967 in another color.

```{r eu_52_67}

eu_52_67 <- gap %>% filter(continent == "Europe",year %in% c(1952,1967)) %>% 
  mutate(year = str_c(year),gdpPercap = log(gdpPercap)) %>% 
  ggplot() + 
  geom_point(aes(x=gdpPercap,y=lifeExp,color = year)) + 
  scale_color_discrete() + 
  labs(title = "GDP and Life Expectancy in Europe",
       x = "GDP per Capita (log)",
       y = "Life Expectancy") + 
  theme_bw() + 
  theme(plot.title = element_text(hjust = .5),) 

eu_52_67
```

